//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ddQuint.Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int TemplateDescriptionCount {
            get {
                return ((int)(this["TemplateDescriptionCount"]));
            }
            set {
                this["TemplateDescriptionCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDir_InputFolder {
            get {
                return ((string)(this["LastDir_InputFolder"]));
            }
            set {
                this["LastDir_InputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDir_TemplateFile {
            get {
                return ((string)(this["LastDir_TemplateFile"]));
            }
            set {
                this["LastDir_TemplateFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDir_ExportAll {
            get {
                return ((string)(this["LastDir_ExportAll"]));
            }
            set {
                this["LastDir_ExportAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDir_ExcelExport {
            get {
                return ((string)(this["LastDir_ExcelExport"]));
            }
            set {
                this["LastDir_ExcelExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDir_PlotsExport {
            get {
                return ((string)(this["LastDir_PlotsExport"]));
            }
            set {
                this["LastDir_PlotsExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDir_ParametersExport {
            get {
                return ((string)(this["LastDir_ParametersExport"]));
            }
            set {
                this["LastDir_ParametersExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDir_ParametersImport {
            get {
                return ((string)(this["LastDir_ParametersImport"]));
            }
            set {
                this["LastDir_ParametersImport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDir_TemplateCreator_Input {
            get {
                return ((string)(this["LastDir_TemplateCreator_Input"]));
            }
            set {
                this["LastDir_TemplateCreator_Input"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDir_TemplateCreator_Export {
            get {
                return ((string)(this["LastDir_TemplateCreator_Export"]));
            }
            set {
                this["LastDir_TemplateCreator_Export"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ddPCR Supermix for Probes (No dUTP)")]
        public string TemplateCreator_Supermix {
            get {
                return ((string)(this["TemplateCreator_Supermix"]));
            }
            set {
                this["TemplateCreator_Supermix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Probe Mix Triplex")]
        public string TemplateCreator_Assay {
            get {
                return ((string)(this["TemplateCreator_Assay"]));
            }
            set {
                this["TemplateCreator_Assay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Copy Number Variation (CNV)")]
        public string TemplateCreator_Experiment {
            get {
                return ((string)(this["TemplateCreator_Experiment"]));
            }
            set {
                this["TemplateCreator_Experiment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemplateCreator_Target1 {
            get {
                return ((string)(this["TemplateCreator_Target1"]));
            }
            set {
                this["TemplateCreator_Target1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemplateCreator_Target2 {
            get {
                return ((string)(this["TemplateCreator_Target2"]));
            }
            set {
                this["TemplateCreator_Target2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemplateCreator_Target3 {
            get {
                return ((string)(this["TemplateCreator_Target3"]));
            }
            set {
                this["TemplateCreator_Target3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemplateCreator_Target4 {
            get {
                return ((string)(this["TemplateCreator_Target4"]));
            }
            set {
                this["TemplateCreator_Target4"] = value;
            }
        }
    }
}
